### PR TITLE
Increase the test coverage of CortexTheseus

### PR DESCRIPTION
**Pull request by DhunterAO**

### CODE REVIEW

**Comment by DhunterAO** [comment]
I wonder whether this PR is too big to review, so maybe we can review and merge it now and start other PRs for new tests.

**Comment by ucwong** [comment]
> I wonder whether this PR is too big to review, so maybe we can review and merge it now and start other PRs for new tests.

OK, I will review and run a full sync for testing

**Comment by DhunterAO** [comment]
OK, I'll try to do this

**Comment by DhunterAO** [comment]
Now the node continues importing new chain segment and I find `FIRST MILESTONE PASS`, so does this mean everything ok? Or I need to wait for this complete?

**Comment by ucwong** [comment]
> Now the node continues importing new chain segment and I find `FIRST MILESTONE PASS`, so does this mean everything ok? Or I need to wait for this complete?

It OK, this log is from torrentfs

**Pull request merged**
