### PR TITLE
signer/rules:use goja instead of otto

### PR DESCRIPTION
**Pull request by ShadowErii**
it seems that goja is faster than otto, and there maybe some problems in otto:https://github.com/robertkrimen/otto/issues/266

### CODE REVIEW

**Comment by ucwong** [comment]
https://github.com/ethereum/go-ethereum/blob/master/signer/rules/rules.go#L102-L114

**Comment by ucwong** [comment]
https://github.com/ethereum/go-ethereum/pull/20599
reference to this

**Comment by ShadowErii** [comment]
more about goja: https://github.com/ethereum/go-ethereum/pull/20470

**Comment by ucwong** [comment]
There is something wrong with this pr
image
So I need to revert this and merge it again when it is ok

**Pull request merged**
